---
output:
  github_document:
    toc: TRUE
editor_options: 
  chunk_output_type: console
---


<!-- # Objective(s) -->
Metadata associated with the FHB dataset
=========


```{r knitr-setup, include=FALSE, eval=TRUE}
options(digits = 1)
require(knitr)
## options
knitr::opts_chunk$set(eval = TRUE, echo = FALSE, cache = TRUE, fig.path = 'Figures/DatasetSummary/', fig.height = 4)
```


---------------------------------------------------------------------------------------


```{r Libraries, eval=TRUE, echo=FALSE, message=FALSE}
library(tidyverse)
library(kableExtra)
```


```{r Load_Data, echo=FALSE, eval=TRUE}
# Read the FHB dataset from the .csv file, specifying the column types:
X <- readr::read_csv("Data/FHBdataset.csv",
                col_types = list(
                  fdate = col_date(),
                  state =  col_factor(c("AR", "DE", "IL", "IN", "KS", "KY", "MD", "MI", "MN", "MO", "ND", "NE", "NY", "OH", "PA", "SD", "WI")),
                  location = col_character(),
                  type = col_factor(c("spring", "winter")),
                  resist = col_factor(c("VS", "S", "MS", "MR")),
                  S = col_double(),
                  T.A.1 = col_double(),
                  T.A.2 = col_double(),
                  T.A.3 = col_double(),
                  T.A.4 = col_double(),
                  T.A.5 = col_double(),
                  D.A.1 = col_double(),
                  D.A.2 = col_double(),
                  D.A.3 = col_double(),
                  P.A.1 = col_double(),
                  P.A.2 = col_double(),
                  P.A.3 = col_double(),
                  P.A.4 = col_double(),
                  P.A.5 = col_double(),
                  RH.A.1 = col_double(),
                  RH.A.2 = col_double(),
                  RH.A.3 = col_double(),
                  VPD.A.1 = col_double(),
                  VPD.A.2 = col_double(),
                  VPD.A.3 = col_double(),
                  VPD.A.4 = col_double(),
                  VPD.A.5 = col_double(),
                  TDD.A.1 = col_double(),
                  TDD.A.2 = col_double(),
                  TDD.A.3 = col_double(),
                  TDD.A.4 = col_double(),
                  TDD.A.5 = col_double(),
                  TDD.A.6 = col_double(),
                  T.MINMAXDIFF.1 = col_double(),
                  T.MINMAXDIFF.2 = col_double(),
                  RH.MINMAXDIFF.1 = col_double(),
                  RH.MINMAXDIFF.2 = col_double(),
                  RH.MINMAXDIFF.3 = col_double(),
                  P.MINMAXDIFF.1 = col_double(),
                  D.MINMAXDIFF.1 = col_double(),
                  D.MINMAXDIFF.2 = col_double(),
                  D.MINMAXDIFF.3 = col_double(),
                  VPD.MINMAXDIFF.1 = col_double(),
                  VPD.MINMAXDIFF.2 = col_double(),
                  VPD.MINMAXDIFF.3 = col_double(),
                  TDD.MINMAXDIFF.1 = col_double(),
                  TDD.MINMAXDIFF.2 = col_double(),
                  TDD.MINMAXDIFF.3 = col_double(),
                  T.SD.1 = col_double(),
                  T.SD.2 = col_double(),
                  T.SD.3 = col_double(),
                  D.SD.1 = col_double(),
                  D.SD.2 = col_double(),
                  D.SD.3 = col_double(),
                  P.SD.1 = col_double(),
                  VPD.SD.1 = col_double(),
                  VPD.SD.2 = col_double(),
                  VPD.SD.3 = col_double(),
                  VPD.SD.4 = col_double(),
                  RH.SD.1 = col_double(),
                  RH.SD.2 = col_double(),
                  TDD.SD.1 = col_double(),
                  TDD.SD.2 = col_double(),
                  TDD.SD.3 = col_double(),
                  TDD.SD.4 = col_double(),
                  MT7 = col_double(),
                  RH7 = col_double(),
                  MT10 = col_double(),
                  RH10 = col_double(),
                  VPD.A.PRE5.12H = col_double(),
                  VPD.A.PRE7.12H = col_double(),
                  VPD.A.PRE10.12H = col_double(),
                  VPD.A.PRE14.12H = col_double(),
                  VPD.A.PRE15.12H = col_double(),
                  VPD.A.POST5.12H = col_double(),
                  VPD.A.POST7.12H = col_double(),
                  VPD.A.POST10.12H = col_double(),
                  VPD.A.POST14.12H = col_double(),
                  VPD.A.POST15.12H = col_double(),
                  DD.A.PRE5.12H = col_double(),
                  DD.A.PRE7.12H = col_double(),
                  DD.A.PRE10.12H = col_double(),
                  DD.A.PRE14.12H = col_double(),
                  DD.A.PRE15.12H = col_double(),
                  DD.A.POST5.12H = col_double(),
                  DD.A.POST7.12H = col_double(),
                  DD.A.POST10.12H = col_double(),
                  DD.A.POST14.12H = col_double(),
                  DD.A.POST15.12H = col_double(),
                  RH.A.PRE5.12H = col_double(),
                  RH.A.PRE5.24H = col_double(),
                  RH.A.PRE7.12H = col_double(),
                  RH.A.PRE10.12H = col_double(),
                  RH.A.PRE10.24H = col_double(),
                  RH.A.PRE14.12H = col_double(),
                  RH.A.PRE14.24H = col_double(),
                  RH.A.PRE15.12H = col_double(),
                  RH.A.PRE15.24H = col_double(),
                  RH.A.POST5.12H = col_double(),
                  RH.A.POST5.24H = col_double(),
                  RH.A.POST7.12H = col_double(),
                  RH.A.POST7.24H = col_double(),
                  RH.A.POST10.12H = col_double(),
                  RH.A.POST14.12H = col_double(),
                  RH.A.POST14.24H = col_double(),
                  RH.A.POST15.12H = col_double(),
                  RH.A.POST15.24H = col_double(),
                  T.A.PRE5.24H = col_double(),
                  T.A.PRE7.24H = col_double(),
                  T.A.PRE10.24H = col_double(),
                  T.A.PRE14.24H = col_double(),
                  T.A.PRE15.24H = col_double(),
                  T.A.POST5.24H = col_double(),
                  T.A.POST7.24H = col_double(),
                  T.A.POST14.24H = col_double(),
                  T.A.POST15.24H = col_double(),
                  .default = col_integer()
                ))

# Subset X to descriptive variables (not weather-based):
X1 <-
  X %>% 
  dplyr::select(id:S) %>%
  # add region as a variable:
  dplyr::left_join(tibble(state = state.abb, region = state.region), by = "state") %>%
  # add division as a variable (New England, Middle Atlantic, South Atlantic, East South Central, West South Central, East North Central, West North Central, Mountain, and Pacific):
  dplyr::left_join(tibble(state = state.abb, division = state.division), by = "state") %>%
  # Add US climate regions:
  # https://www.ncei.noaa.gov/access/monitoring/reference-maps/us-climate-regions 
  dplyr::mutate(climzone = "NA") %>%
  dplyr::mutate(climzone = replace(climzone, state %in% c("CT", "DE", "ME", "MD", "MA", "NH", "NJ", "NY", "PA", "RI", "VT"), "Northeast")) %>%
  dplyr::mutate(climzone = replace(climzone, state %in% c("IA", "MI", "MN", "WI"), "Upper Midwest")) %>%
  dplyr::mutate(climzone = replace(climzone, state %in% c("IL", "IN", "KY", "MO", "OH", "TN", "WV"), "Ohio Valley")) %>%
  dplyr::mutate(climzone = replace(climzone, state %in% c("MT", "NE", "ND", "SD", "WY"), "Northern Rockies and Plains")) %>%
  dplyr::mutate(climzone = replace(climzone, state %in% c("AR", "KS", "LA", "MS", "OK", "TX"), "South")) %>%
  dplyr::mutate(climzone = factor(climzone, levels = c("Northeast", "Upper Midwest", "Ohio Valley", "Northern Rockies and Plains", "South")))
```


# Basic summaries of the observational data matrix
```{r Functions, eval=TRUE, echo=FALSE}
my.summary.fxn <- function(data, .x) {
  # dot plot of the data
  # Args:
  #  data = in this case, X1
  #  .x = unquoted variable for the x-axis
  # Returns:
  #  a dotplot of the frequency of the x variable
  #
  x <- enquo(.x)
  
  data %>%
  ggplot(aes(x = !!x, y = n)) +
  geom_segment(aes(xend = !!x, yend = 0)) +
  geom_point(size = 4, colour = "orange") +
  coord_flip() +
  theme_bw() +
  xlab("") +
  ylab("Frequency") +
  theme(# remove the grid lines for y:
    panel.grid.major.y = element_blank())
}
```


## By year
```{r Obs-matrix-by-year-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::count(year) %>%
  dplyr::mutate(year = factor(year)) %>%
  my.summary.fxn(., year) 
```


## By state
```{r Obs-matrix-by-state-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::count(state) %>%
  dplyr::mutate(state = factor(state)) %>%
  my.summary.fxn(., state)
```


## By climate region
```{r Obs-matrix-by-climate-region-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::count(climzone) %>%
  my.summary.fxn(., climzone)
```


## By wheat type
```{r Obs-matrix-by-type-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::count(type) %>%
  my.summary.fxn(., type)
```


## By resistance level
```{r Obs-matrix-by-resist-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::count(resist) %>%
  my.summary.fxn(., resist)
```


## By maize residue presence (absence)
```{r Obs-matrix-by-residue-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::mutate(corn = factor(corn, levels = c(0, 1), labels = c("No residue", "Residue"))) %>%
  dplyr::count(corn) %>%
  dplyr::filter(!is.na(corn)) %>%
  my.summary.fxn(., corn)
```


## By wheat type and resistance level
```{r Obs-matrix-by-type-and-resist-graph, eval=TRUE, echo=FALSE}
X1 %>%
  dplyr::count(type, resist) %>%
  ggplot(aes(x = resist, y = n)) +
  geom_segment(aes(xend = resist, yend = 0)) +
  geom_point(size = 4, colour = "orange") +
  coord_flip() +
  facet_wrap(~type, scales = "free_y") +
  theme_bw() +
  xlab("Resistance") +
  ylab("Frequency") +
  theme(# remove the grid lines for y:
    panel.grid.major.y = element_blank())
```


## By wheat type and climate region
```{r Obs-matrix-by-climate-region-and-type-graph, eval=TRUE, echo=FALSE}
# dot plot
X1 %>%
  dplyr::count(climzone, type) %>%
  ggplot(aes(x = type, y = n)) +
  geom_segment(aes(xend = type, yend = 0)) +
  geom_point(size = 4, colour = "orange") +
  coord_flip() +
  facet_wrap(~climzone, scales = "free_y") +
  theme_bw() +
  xlab("Type") +
  ylab("Frequency") +
  theme(# remove the grid lines for y:
    panel.grid.major.y = element_blank())
```


-----------------------------------------------


```{r Read-Metadata, eval=TRUE, echo=FALSE, results='hide'}
# Read in the data from the .csv file:
io <- readr::read_csv("Data/VariableMetaData.csv", show_col_types = FALSE)
```


--------------------------------------------


# Parsing the global set of variables
* there are `r nrow(io)` weather-based variables

```{r GlobalVars-Parsing-Examples, eval=FALSE, echo=FALSE}
# Examples of ways to parse these variables
#  (i) Example: all pre-anthesis starting at least 25 days pre-
io %>%
  dplyr::filter(period == "pre", win_start_day >= 25) %>%
  dplyr::count(type)

# (ii) Most variables count the no. hr <cond>
io %>%
  dplyr::count(metric, time_step)

# (iii) But there are 8 which count daily <cond> for the time period specified:
io %>%
  dplyr::filter(metric == "count", time_step == "daily") %>%
  dplyr::select(variable_name, starts_with("win_"))

# (iv) About an even split between pre and post anthesis variables:
io %>%
  dplyr::count(period)

# (v) Most variables are anchored at anthesis and then extend either into the pre- or post-anthesis period. A few variables span the pre- to post- period, some are confined to windows in the pre- period (not extending to anthesis), and there is one variable that is strictly in the post period. 
io %>%
  dplyr::count(win_start_period, win_end_period)
```


## Type

* D = dewpoint
* P = barometric pressure
* RH = relative humidity
* T = air temperature
* TDD = temperature-dewpoint depression
* TRH =  a combination of temperature and relative humidity conditions
* VPD = vapor pressure deficit

```{r GlobalVars-type, eval=TRUE, echo=FALSE}
# By type:
io %>%
  dplyr::count(type) %>%
  kable(.)
```

## Metric
* i.e., does the variable summarize a count (e.g., no. of hr) or mean?

```{r GlobalVars-metric, eval=TRUE, echo=FALSE}
# By metric:
io %>%
  dplyr::count(metric) %>%
  kable(.)
```

## Window start day
* the start day of the window which the variable summarizes

```{r GlobalVars-win-start-day, eval=TRUE, echo=FALSE}
# By win_start_day:
io %>%
  dplyr::count(period, win_start_day) %>%
  # Easier to visualize:
  ggplot(., aes(x = n, y = win_start_day)) +
  geom_segment(aes(yend = win_start_day), xend = 0, colour = "grey50") +
  geom_point(size = 3, colour = "cornflowerblue") +
  facet_wrap(~period, ncol = 3, scales = "free_x") +
  theme_bw() +
  xlab("No. of variables") +
  ylab("Window start day") +
  # No horizontal grid lines:
  theme(panel.grid.major.y = element_blank() )
```

## Window length
* the length (days) of the window the variable summarizes

```{r GlobalVars-win-length, eval=TRUE, echo=FALSE}
# By win_length:
io %>%
  dplyr::count(period, win_length) %>%
  # Easier to visualize:
  ggplot(., aes(x = n, y = win_length)) +
  geom_segment(aes(yend = win_length), xend = 0, colour = "grey50") +
  geom_point(size = 3, colour = "cornflowerblue") +
  facet_wrap(~period, ncol = 3) +
  theme_bw() +
  xlab("No. of variables") +
  ylab("Window length") +
  # No horizontal grid lines:
  theme(panel.grid.major.y = element_blank() )
```


-----------------------------------------------


# Computational environment
```{r SessionInfo, eval=TRUE, echo=FALSE, results='markup'}
R.Version()$version.string
R.Version()$system
sessionInfo()
```